### ISSUE TITLE
add no-callback version of model get

### ISSUE THREAD

**Issue by jdubie** [ladderlife/cambo#24]
add arity without callback that just returns the result. the reason there's a callback is for async calling in the browser? if you think this is an OK thing to do then assign to me.

https://github.com/ladderlife/cambo/blob/master/src/cambo/model.cljc#L85

**Comment by eyston** [comment]
make it for `clj` only

- [ ] add arity without callback -- calls just defers to get with `nil` callback
- [ ] `get` returns a `promise`, wrap callback, call callback if not nil and deliver promise

### example:

```clj
@(get model [pathsets])
@(get model [pathsets] cb)
```

**Comment by eyston** [comment]
this might be overkill and just blocking if not passed a cb is legit~
